### ISSUE TITLE
[Bug]: Colorful Azaleas using same package as Bovine and Buttercup class

### ISSUE THREAD

**Issue by TelepathicGrunt** [terrarium-earth/ColorfulAzaleas#10]
### Bug Description

This line here is the the issue
https://github.com/terrarium-earth/ColorfulAzaleas/blob/03df7d83b92b9bcd93f5b8ac92df8f27a8f95934/Forge/src/main/java/com/kekie6/colorfulazaleas/ForgeRegistrationFactory.java#L1

Causes this error which I reported on the wrong repo:
https://github.com/MerchantPug/bovines-and-buttercups/issues/8

**Copy pasted from above link:** 

I was testing some mod compat work but then found that Colorful Azalea and Bovine and Buttercups mod will not run together. Each one can run separately. Using latest Forge and latest version of each mod for 1.19.2.
https://www.curseforge.com/minecraft/mc-mods/colorfulazaleas
https://www.curseforge.com/minecraft/mc-mods/bovines-and-buttercups

The issue is I am not sure what this error means or how Colorful Azalea is even involved. The latest.log file had no info but the launcher.log did.
Game/game () Info Exception in thread "main" java.lang.module.ResolutionException: Modules colorfulazaleas and bovinesandbuttercups export package net.merchantpug.bovinesandbuttercups to module minecraft
https://paste.ee/p/eN8ok

![image](https://user-images.githubusercontent.com/40846040/215330051-d8aa8492-7aaa-4615-bdfd-109e1e3181b3.png)

### How to Reproduce?

Put on Colorful Azaleas and Bovine and Buttercups mod together. Try to run the game
![image](https://user-images.githubusercontent.com/40846040/215330071-9f29d43a-5382-4f78-9897-57ca530946d7.png)

### Expected Behavior

Not crash

### Version

2.0.0

### Mod Loader Version

1.19.2 - 43.2.3

### Mod Loader

Forge

### Logs or additional context

https://paste.ee/p/eN8ok

**Comment by MerchantPug** [comment]
ah, must've been an issue with my multiloader porting for this mod, I guess I can PR a fix for it.

**Comment by MerchantPug** [comment]
^^^

**Comment by MerchantPug** [comment]
I copied a few Bovines classes over for the purpose of making my life easier for this Modtoberfest PR, I just forgot to change the package names I guess because I thought IntelliJ handled it for me..

**Comment by Kekie6** [comment]
thank you for fixing this, I added it to the latest push as i was also making some other changes.
it should all be fixed in the next update.

**Comment by Kekie6** [comment]
thank you for fixing this, I added it to the latest push as i was also making some other changes.
it should all be fixed in the next update.
