### ISSUE TITLE
[Feature Request]: 1.20.1 version (Forge/Fabric)

### ISSUE THREAD

**Issue by Gamemassa** [terrarium-earth/ColorfulAzaleas#24]
### Is your feature request related to a problem?

Hi, I'm just curious if a 1.20.1 version of Colorful Azaleas is in the works? No rush, just would like to know if it's planned.

### Mod Version

N/A

### Mod Loader Version

1.20.1

### Mod Loader

N/A

**Comment by walrhe93** [comment]
I'm also really waiting for it

**Comment by vinnyg0621** [comment]
@Kekie6 @DaFuqs wait, fabric 1.20 is done, but why is there no forge?

**Comment by DaFuqs** [comment]
I don't vibe with LexForge

**Comment by vinnyg0621** [comment]
> I don't vibe with LexForge

what do you mean, so you're gonna keep it on fabric only on 1.20?
no fair!!! neoforge and lexforge are completely compatible with each other on 1.20.1!!!!!

**Comment by vinnyg0621** [comment]
also @DaFuqs why is your name "da fu**s"?
