### ISSUE TITLE
Flowering Azalea saplings and leaves are not tagged minecraft:flowers

### ISSUE THREAD

**Issue by TelepathicGrunt** [terrarium-earth/ColorfulAzaleas#5]
Noticed this when testing All of fabric 6 modpack in 1.19.2. Just something small so bees can pollinate these azalea flower blocks. Vanilla tags their flowering azalea and flowering azalea leaves blocks as flowers 

![image](https://user-images.githubusercontent.com/40846040/202873806-a197b68e-638c-4d60-adb6-e6b24d67d837.png)

![image](https://user-images.githubusercontent.com/40846040/202873844-608447e9-778c-47c5-9e6c-dc12f8e5e471.png)

**Comment by DayTheMagpie** [comment]
The complete lack of tags causes a _lot_ of other issues as well. Hoes don't break the leaf blocks efficiently because they aren't recognized as leaves, tree fell mods don't work with the colored azalea trees, and texture packs like Motschen's Better Leaves are totally incompatible as a result.
