### ISSUE TITLE
Azalea wood log and door variants are missing basic block tags

### ISSUE THREAD

**Issue by Not-February** [terrarium-earth/ColorfulAzaleas#6]
``Minecraft 1.19.2``
``Forge 43.1.52``
``Colorful Azaleas 2.0.0``

Comparing with both a regular oak tree and another modded tree, there are some tags that are simply not present on the azalea variants of logs. Not having these can at times interfere with compatibility with other mods, like those that detect whether something in the world is a tree or not based on its block tags.

These are the block tags from minecraft's namespace that seem to be missing on azalea wood variants when looking at the logs with the debug screen toggled on:

``minecraft:logs``
``minecraft:logs_that_burn``
``minecraft:overworld_natural_logs``
``minecraft:snaps_goat_horn``
``minecraft:parrots_spawnable_on``
``minecraft:completes_find_tree_tutorial``

EDIT: I have also noticed that door variants are missing the ``minecraft:doors`` and ``minecraft:wooden_doors`` block tags, which makes it impossible for villagers to open and close them.

**Comment by Kekie6** [comment]
Done, I did all the tags for buttons, stairs, slabs, doors, trapdoors, planks, logs, woods and pressureplates too! :D
