### ISSUE TITLE
Azalea wood variant crafting dupe

### ISSUE THREAD

**Issue by Not-February** [terrarium-earth/ColorfulAzaleas#7]
This applies to every variant of azalea wood added by this mod.

By default there are recipes for both crafting logs into wood, and also wood back into logs... but the output of the latter recipe gives you more logs than you started with. So as long as you start with enough logs to craft into wood and back, you can just get an endless amount of azalea logs by using this crafting loop.

Since there isn't a recipe to turn wood back into logs in vanilla anyways, this issue could be sidestepped entirely by just not including the recipes to turn wood back into logs.

Observed with:
``Minecraft 1.19.2``
``Forge 43.2.1``
``Colorful Azaleas 2.0.0``

**Comment by Kekie6** [comment]
Thank you for letting me know of this issue. I fixed the recipes now, which means there are no recipes anymore for turning woods back into logs and logs can only be turned into wood for a 4:3 ratio. This is the same as vanilla minecraft :)
