### ISSUE TITLE
Fences dont connect to eachother

### ISSUE THREAD

**Issue by pumpimpie** [terrarium-earth/ColorfulAzaleas#8]
it seems like the fences for every type of wood in the azalea mod don't connect to each other. They will connect to full blocks like oak planks and even fence gates but won't connect to fences. If u put two tecal fences next to each other they won't touch, and you can walk in between the fences. They also don't connect to vanilla fences, so if you put rose fence next to a vanilla oak fence they won't touch. This goes for all types of azalea fences though, not just a single type.

![2022-12-29_17 27 27](https://user-images.githubusercontent.com/121644075/210017214-ea67f180-2553-4a19-8f00-e9d0dd6fe76b.png)

![2022-12-29_17 27 34](https://user-images.githubusercontent.com/121644075/210017217-e9a3f455-3102-4d20-9974-cbc614cb97bf.png)

**Comment by Kekie6** [comment]
![image](https://user-images.githubusercontent.com/79649631/216828074-e3004c9e-506a-4a13-937f-3d27c0617c59.png)
fixed! :D
