### ISSUE TITLE
[Bug]: Infinite Wood from Colorful Azaleas

### ISSUE THREAD

**Issue by TheonlyTazz** [terrarium-earth/ColorfulAzaleas#9]
### Bug Description

1 of any of the Azalea Wood from the Colorful Azaleas mod can be crafted into 4 of the respective Azalea Logs.
Then, the Azalea Log that was just crafted from the Wood block can be crafted back into 3 of the Azalea Wood blocks.
Basically you can infinitely craft Azalea wood by crafting the Wood block into 4 logs and then each log into 3 Wood, and so on.
Hopefully this makes sense.

### How to Reproduce?

1- Put Azalea Wood block in crafting grid and select the option to craft it into 4 Azalea Logs
2- Put the Azalea Log(s) in crafting grid and select the option to craft 1 Azalea Log into 3 Azalea Wood blocks
3- Repeat infinitely

### Expected Behavior

Not to be able to infinitely craft this item

### Version

ColourfulAzaleas - FABRIC 1.19.2 - (1.0.0).jar

### Mod Loader Version

1.19.2 0.14.12

### Mod Loader

Fabric

### Logs or additional context

https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2561

**Comment by Kekie6** [comment]
same issue as previously reported. but fixed now :)
